### PR TITLE
Add initial data files

### PR DESCRIPTION
**Pull request by wddgit**
Add initial data files that will be used in test of the FEDRawDataCollection format. These will be read by future releases to verify backward compatibility.

### CODE REVIEW

**Comment by wddgit** [comment]
please test

FYI @makortel

**Comment by smorovic** [comment]
+1

**Comment by perrotta** [comment]
+1
- needed by https://github.com/cms-sw/cmssw/pull/41494

**Comment by perrotta** [comment]
merge

**Pull request merged**
